#production:
#  adapter: postgresql
#  encoding: unicode
#  database:
#  username:
#  password:
#  host:
#  port: 5432

development:
  adapter: <%= ENV["DEVELOPMENT_ADAPTER"] %>
  encoding: <%= ENV["DEVELOPMENT_UNICODE"] %>
  database: <%= ENV["DEVELOPMENT_DATABASE"] %>
  username: <%= ENV["DEVELOPMENT_USERNAME"] %>
  password: <%= ENV["DEVELOPMENT_PASSWORD"] %>
  host: <%= ENV["DEVELOPMENT_HOST"] %>
  port: <%= ENV["DEVELOPMENT_POST"] %>

test:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/test.sqlite3